#!/bin/sh

# A simple install script for the dotfiles.

process_title() 
{
    t=${1%?}
    T=$(echo "$t" | tr '[:lower:]' '[:upper:]' | sed 's/./& /g' | xargs)
    title_length=$(expr ${#T} / 2)
    printf %$(expr 40 + $title_length)s "$T" 
    printf "\n"
    printf %80s | tr " " "*"
    printf "\n"
}


for d in */; do
    if [ -d $d ]; then 
        if [ ! "$d" = "install" ]; then 
            oldpwd=$PWD
            process_title "$d"
            cd $d
            ./install
            cd $oldpwd
        fi
    fi
done

