#!/bin/bash

# A small script to toggle between US and Icelandic keyboard.
# Meant to be used with xbindkeys.

XMODMAPFILE="/home/anton/.Xmodmap"
CURRENT=$(setxkbmap -print | awk -F"+" '/xkb_symbols/ {print $2}')

if [ "$CURRENT" = "us" ]
then
	setxkbmap is
elif [ "$CURRENT" = "is" ]
then
	setxkbmap us
fi

xmodmap "$XMODMAPFILE"
