#!/usr/bin/sh

echo "[::] Making sure that $HOME/.config/${PWD##*/} exists..."
[ ! -d $HOME/.config/${PWD##*/} ] && mkdir $HOME/.config/${PWD##*/} 

echo "[::] Creating symlink from $PWD/config to $HOME/.config/${PWD##*/}/config"
ln -s $PWD/config $HOME/.config/${PWD##*/}/config
