#!/bin/sh

if [ ! -d $HOME/.xmonad ]; then
	echo "[::] $HOME/.xmonad not found, creating..."
	mkdir $HOME/.xmonad
fi

echo "[::] Creating symlink from $PWD/xmonad.hs to $HOME/.xmonad/xmonad.hs"
ln -s $PWD/xmonad.hs $HOME/.xmonad/xmonad.hs

echo "[::] Creating symlink from $PWD/build to $HOME/.xmonad/build"
ln -s $PWD/build $HOME/.xmonad/build
